"use client";

import Link from "next/link";
import Header from "./components/layouts/header/Header";
import Scrolldown from "./components/scrolldown/Scrolldown";
import Projects from "./components/projects/Projects";
import Expertise from "./components/Expertise";
import Typewritter from "./components/typewritter/Typewritter";

export default function Home() {
  return (
    <main className="min-h-screen" id="main">
      <Header />
      {/* Banner */}
      <section className="min-h-screen mx-auto px-4 py-24 relative flex justify-center">
        <div className="container mx-auto">
          <h1 className="heading_1">
            Websites & <br />
            Design
          </h1>
          <div className="flex md:flex-row flex-col justify-between my-20">
            <div className="md:w-6/12 md:mb-0 mb-10">
              <h3 className="font-semibold text-lg">Let&apos;s Talk</h3>
              <Link
                href="mailto:stephanoxuan@gmailcom?subject=Come%20Work%20for%20Us!&body=Please%20come%20and%20work%20for%20us%20!%0D%0A%0D%0ACheers%2C%0D%0AHappy%20Company"
                target="_blank"
                className="mt-3 hover:text-neutral-400"
              >
                stephanoxuan@gmail.com
              </Link>
            </div>
            <div className="md:w-6/12">
              <p className="text-justify">
                Unlock the full potential of your online presence with our
                expert website development services &#8722; let&apos;s create a
                website that truly represents your brand and engages your
                audience effectively
              </p>
            </div>
          </div>
        </div>
        <div className="absolute bottom-10">
          <Scrolldown />
        </div>
      </section>
      {/* Banner End */}
      {/* Project */}
      <section className="mx-auto px-4 py-24 flex justify-center" id="project">
        <div className="container">
          <div className="flex flex-row justify-between">
            <div>
              <h2 className="heading_2">Projects</h2>
              <p className="text-justify md:w-8/12 sm:w-10/12 w-full mt-3">
                I excel in collaborative project environments, leveraging my
                strong communication skills and adaptability to seamlessly work
                with others, ensuring project success and team cohesion.
              </p>
            </div>
            {/* <div>
              <a>More</a>
            </div> */}
          </div>
          {/* <div className="grid grid-cols-[repeat(auto-fit,_33.333333%)] md:gap-4 gap-8 mx-auto mt-10 justify-center">
            <Projects />
            <Projects />
            <Projects />
          </div> */}
          <div className="flex flex-wrap mx-auto mt-10 justify-center">
            <Projects />
          </div>
        </div>
      </section>
      {/* Project End */}
      {/* Expertise */}
      <section
        className="mx-auto px-4 py-24 flex justify-center"
        id="expertise"
      >
        <div className="container">
          <div className="flex flex-row justify-between">
            <div>
              <h2 className="heading_2">Expertise</h2>
            </div>
          </div>
          <div className="flex flex-wrap mx-auto mt-10 justify-center">
            <Expertise />
          </div>
        </div>
      </section>
      {/* Expertise End */}
      {/* Moving Words  */}
      <section className="mx-auto flex justify-center bg-neutral-950">
        <Typewritter />
      </section>
      {/* Moving Words End */}
      {/* Testimonials */}
      <section className="mx-auto px-4 py-24 flex justify-center">
        <div className="container">
          <div className="flex flex-row justify-between">
            <div>
              <h2 className="heading_2">Testimonials</h2>
              <div className="flex flex-wrap justify-between">
                <div className="md:w-9/12 w-full">
                  <p className="md:mb-0 mb-5 mt-5 md:text-2xl text-lg text-justify">
                    &quot;My colleague is exceptional—dedicated,
                    detail-oriented, and a great communicator. Their commitment,
                    collaborative spirit, and innovative problem-solving
                    significantly contribute to our team&apos;s success.
                    Reliable, positive, and insightful, they bring valuable
                    perspectives. It&apos;s a pleasure to work with someone so
                    capable and team-oriented. &#40; Generated by ChatGPT &#41;
                    &quot;
                  </p>
                </div>
                <div className="md:w-3/12 w-full text-end self-end">
                  <h4 className="text-lg font-semibold">Nigel</h4>
                  <span className="text-neutral-400">
                    Liverpool Manager <br />
                    &#40; When watching from home &#41;
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      {/* Testimonials End */}
      {/* Contact Us */}
      <section className="mx-auto flex justify-center py-24" id="contact">
        <div className="flex flex-col">
          <h1 className="heading_1">Call Me Maybe</h1>
          <div className="flex justify-center mt-10">
            <Link
              href="mailto:stephanoxuan@gmailcom?subject=Come%20Work%20for%20Us!&body=Please%20come%20and%20work%20for%20us%20!%0D%0A%0D%0ACheers%2C%0D%0AHappy%20Company"
              target="_blank"
              className="btn btn-neutral text-lg h-full py-5 px-7 "
            >
              Contact Now
            </Link>
          </div>
        </div>
      </section>
      {/* Contact Us End */}
    </main>
  );
}
